
// 🚀 Auto-generated by scripts/generateIconMap.js
// Do NOT edit this file manually.

import { ImageSourcePropType } from "react-native";

export type IconName = "ac_icon" | "ac_install_icon" | "ac_repair" | "ac_repair_icon" | "appliances" | "battery_replace_icon" | "catering_help_icon" | "ceiling_fan_icon" | "cleaning" | "drywall" | "electricity" | "exhaust_fan_icon" | "fencing" | "fridge_deep_servicing_icon" | "geyser_installation_icon" | "hvac" | "inverter_installation_icon" | "leak_repair-icon" | "mcb_replacement_icon" | "moving" | "packing_unpacking_icon" | "painting" | "plumbing" | "roof" | "switchboard_repair_icon" | "water" | "wm_icon" | "yoga_session_icon" | "default";

export const iconMap: Record<IconName, ImageSourcePropType> = {
  "ac_icon": require("../../assets/Icons/ac_icon.png"),
  "ac_install_icon": require("../../assets/Icons/ac_install_icon.png"),
  "ac_repair": require("../../assets/Icons/ac_repair.png"),
  "ac_repair_icon": require("../../assets/Icons/ac_repair_icon.png"),
  "appliances": require("../../assets/Icons/appliances.png"),
  "battery_replace_icon": require("../../assets/Icons/battery_replace_icon.png"),
  "catering_help_icon": require("../../assets/Icons/catering_help_icon.png"),
  "ceiling_fan_icon": require("../../assets/Icons/ceiling_fan_icon.png"),
  "cleaning": require("../../assets/Icons/cleaning.png"),
  "drywall": require("../../assets/Icons/drywall.png"),
  "electricity": require("../../assets/Icons/electricity.png"),
  "exhaust_fan_icon": require("../../assets/Icons/exhaust_fan_icon.png"),
  "fencing": require("../../assets/Icons/fencing.png"),
  "fridge_deep_servicing_icon": require("../../assets/Icons/fridge_deep_servicing_icon.png"),
  "geyser_installation_icon": require("../../assets/Icons/geyser_installation_icon.png"),
  "hvac": require("../../assets/Icons/hvac.png"),
  "inverter_installation_icon": require("../../assets/Icons/inverter_installation_icon.png"),
  "leak_repair-icon": require("../../assets/Icons/leak_repair-icon.png"),
  "mcb_replacement_icon": require("../../assets/Icons/mcb_replacement_icon.png"),
  "moving": require("../../assets/Icons/moving.png"),
  "packing_unpacking_icon": require("../../assets/Icons/packing_unpacking_icon.png"),
  "painting": require("../../assets/Icons/painting.png"),
  "plumbing": require("../../assets/Icons/plumbing.png"),
  "roof": require("../../assets/Icons/roof.png"),
  "switchboard_repair_icon": require("../../assets/Icons/switchboard_repair_icon.png"),
  "water": require("../../assets/Icons/water.png"),
  "wm_icon": require("../../assets/Icons/wm_icon.png"),
  "yoga_session_icon": require("../../assets/Icons/yoga_session_icon.png"),
  "default": require("../../assets/Icons/default.png"),
};
