
// 🚀 Auto-generated by scripts/generateIconMap.js
// Do NOT edit this file manually.

import { ImageSourcePropType } from "react-native";

export type IconName = "appliances" | "cleaning" | "drywall" | "electricity" | "fencing" | "hvac" | "moving" | "painting" | "plumbing" | "roof" | "water" | "default";

export const iconMap: Record<IconName, ImageSourcePropType> = {
  "appliances": require("../../assets/Icons/appliances.png"),
  "cleaning": require("../../assets/Icons/cleaning.png"),
  "drywall": require("../../assets/Icons/drywall.png"),
  "electricity": require("../../assets/Icons/electricity.png"),
  "fencing": require("../../assets/Icons/fencing.png"),
  "hvac": require("../../assets/Icons/hvac.png"),
  "moving": require("../../assets/Icons/moving.png"),
  "painting": require("../../assets/Icons/painting.png"),
  "plumbing": require("../../assets/Icons/plumbing.png"),
  "roof": require("../../assets/Icons/roof.png"),
  "water": require("../../assets/Icons/water.png"),
  "default": require("../../assets/Icons/default.png"),
};
